lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
    public_key: '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: 'email'
    token_ttl: 86400
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Token
            name: Authorization
